chore: Dockerfile added to the project

diff --git a/.github/workflows/build-check.yml b/.github/workflows/build-check.yml
--- a/.github/workflows/build-check.yml
+++ b/.github/workflows/build-check.yml
@@ -69,16 +69,26 @@ jobs:
           SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
 
         run: |
-          echo "$SSH_KEY" > $GITHUB_WORKSPACE/coffeeshopkey.pem
-          chmod 600 $GITHUB_WORKSPACE/coffeeshopkey.pem
-          ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/coffeeshopkey.pem ubuntu@ec2-16-171-16-255.eu-north-1.compute.amazonaws.com << 'EOF'
-            docker stop $(docker ps -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/voice-powered-quiz-be:v1.0)
-            docker rm $(docker ps -a -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/voice-powered-quiz-be:v1.0)
-            docker rmi $(docker images -q --filter reference=${{ secrets.DOCKER_USERNAME }}/voice-powered-quiz-be:v1.0)
-            docker pull ${{ secrets.DOCKER_USERNAME }}/voice-powered-quiz-be:v1.0
-            docker stop $(docker ps -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/voice-powered-quiz-be:v1.0)
-            docker run -d -p 8080:8080 \
-            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
-            -e MONGO_URI=${{ secrets.MONGO_URI }} \
-            ${{ secrets.DOCKER_USERNAME }}/voice-powered-quiz-be:v1.0
-          EOF
+
+            # Save the SSH key to a file and set appropriate permissions
+            echo "$SSH_KEY" > $GITHUB_WORKSPACE/coffeeshopkey.pem
+            chmod 600 $GITHUB_WORKSPACE/coffeeshopkey.pem 
+
+            # Deploy the app to EC2 instance
+            ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/coffeeshopkey.pem ubuntu@ec2-16-171-16-255.eu-north-1.compute.amazonaws.com << EOF
+          
+              # Stop, remove, and clean up old containers/images
+              docker stop \$(docker ps -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/voice-powered-quiz-be:v1.0) || true
+              docker rm \$(docker ps -a -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/voice-powered-quiz-be:v1.0) || true
+              docker rmi \$(docker images -q --filter reference=${{ secrets.DOCKER_USERNAME }}/voice-powered-quiz-be:v1.0) || true
+
+              # Pull the latest image
+              docker pull ${{ secrets.DOCKER_USERNAME }}/voice-powered-quiz-be:v1.0
+
+              # Stop the running container and start a new one
+              docker stop \$(docker ps -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/voice-powered-quiz-be:v1.0) || true
+              docker run -d -p 8080:8080 \
+                -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
+                -e MONGO_URI=${{ secrets.MONGO_URI }} \
+              ${{ secrets.DOCKER_USERNAME }}/voice-powered-quiz-be:v1.0
+            EOF
